### PR TITLE
Create login page

### PR DESCRIPTION
**Pull request by gellend**
Create login page using Material UI, still need to improve for the design

### CODE REVIEW

**Comment by harryakbar** [comment]
Why do you remove the package-lock.json broh?

By the way you can also add other reviewers yaa, for @ryanadiputraa and @jacenyang

**Comment by gellend** [comment]
> Why do you remove the package-lock.json broh?
> By the way you can also add other reviewers yaa, for @ryanadiputraa and @jacenyang

Sorry mas, the package-lock.json was committed accidentally. I already add the file back. Thank you!

**Review by harryakbar — APPROVED** [review]
Approved

**Comment by harryakbar** [comment]
Btw, can you check the netlify log?
```
82:48  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```

There's a rule for quote usage, I think we don't need the rules. You can remove the rule `react/no-unescaped-entities`

Learn here:
https://nextjs.org/docs/basic-features/eslint#disabling-rules

**Pull request merged**
